program: classification_wandb.py
project: multiling_ili-detection-revised
entity: llm_finetuners
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001
  batch_size:
    values : [16, 32]
  epochs:
    value: 10